# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WAPY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WAPY
  pod 'FlexibleSteppedProgressBar', :git => 'https://github.com/Minitour/FlexibleSteppedProgressBar.git', :branch => 'master'
  pod 'PKHUD', '~> 5.0'
  pod 'AZTabBar'
  pod 'AZDialogView'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Eureka'
end
